bokeh-app/main.py

addding option to switch hemisphere

hemisphere switch 

---

bokeh-app/main.py

Add preliminary functionality to select Sea Ice Extent or Sea Ice Area.
Signed-off-by: Michael Yartys <michael.yartys@protonmail.com>

main: add SIE/SIA selection

---

bokeh-app/main.py

This will make the plot use all of the available space.

main: make sure plot uses available space

---

bokeh-app/main.py

Add a label to the top of the page to signify that the project is still
WIP.
Signed-off-by: Michael Yartys <michael.yartys@protonmail.com>

main: add WIP label

---

bokeh-app/main.py
bokeh-app/toolkit.py

Move functions into a separate file.

Refactor code

---

bokeh-app/main.py

Make sure that the zoom is reset when the data is updated.
Signed-off-by: Michael Yartys <michael.yartys@protonmail.com>

main: reset zoom when updating data

---

bokeh-app/main.py

This PR deals with adding labels to display the following inside of the plot area:
I plan to add the climatology period and the period for the min/max values at the top of the plot, like in the static PNGs: https://osisaf-hl.met.no/archive/osisaf/sea-ice-index/v2p1/nh/en/osisaf_nh_sie_daily-2years.png
In order to do that I need to figure out a way to make sure that the label stays in the upper left corner even when the plot is zoomed in/out or dragged around. I've already managed to do this with the label in the lower left corner.
Here's a binder instance for this PR: https://mybinder.org/v2/gh/huaracheguarache/sea-ice-index-viz/text_label?urlpath=%2Fproxy%2F5006%2Fbokeh-app

[WIP] Add labels to plot

---

bokeh-app/main.py
bokeh-app/toolkit.py

This PR adds all of the available regions, and it makes changes to the zoom shortcut logic so that it works for all regions.

Add new regions

---

bokeh-app/main.py

Use Select instead of Dropdown as a widget for zoom shortcuts to be able to see the currently selected zoom. Also, stop resetting the zoom after an index or area change, just recalculate the zoom level form the new data instead.

Rework zoom shortcut selector and logic

---

bokeh-app/main.py

Simplify the legends by combining percentiles and median into one legend, and minimum and maximum into another.

Simplify legends

---

bokeh-app/main.py

Add a loading indicator to display when data is loading.

Add a loading indicator

---

docker/bokeh/requirements.txt
environment.yml

Add panel dependency after wrapping things in panel.

Add panel dependency

---

bokeh-app/main.py

* Change the spinner colour to dark grey, and make sure that it's stretched both vertically and horizontally.
* Format the tooltip index values so that they're always displayed as a 3 decimal number.

Visual tweaks

---

bokeh-app/main.py

Add a label with info about latest data point

---

docker/bokeh/requirements.txt
environment.yml

which includes an explicit guard against
runtime error panel issues/3552

pin panel version

---

bokeh-app/main.py

main: check if data file is available

---

bokeh-app/main.py

main: Change 2 years plot preset

---

bokeh-app/main.py
bokeh-app/toolkit.py

Add global area selection

---

README.md
bokeh-app/main.py
bokeh-app/toolkit.py
docker/bokeh/requirements.txt
environment.yml

Closes #12 and updates the Panel requirement to 0.14.2.

Decade curves

---

bokeh-app/main.py
docker/bokeh/entrypoint.sh

* Fix docker entrypoint to use panel instead of bokeh.
* Improve the formatting of the area selection widget.
* Fix the data updating function to use the correct range for the 1980s climatology.
* Make the text label dynamic by only displaying climatology and min/max info when they're visible.
Closes: #71

Several improvements

---

bokeh-app/main.py
bokeh-app/toolkit.py

This PR adds the possibility to plot the yearly min/max values in the form of circles/triangles, respectively.
Closes: #77

Add yearly min/max functionality

---

bokeh-app/main.py
bokeh-app/toolkit.py

Add more non-sequential colours maps

---

bokeh-app/main.py

Show an error message to the user when the data for the requested region is unavailable.
Resolves: #85

Warn user when data is unavailable

---

bokeh-app/main.py

Rewrite the text label callback to python and make sure that it properly updates the reference period.

Fix text label callback

---

bokeh-app/monthly/main.py

* Use gridspec to improve layout.
* Change the default month to January.
* Add forgotten axis labels.

Monthly tweaks

---

bokeh-app/monthly/main.py
bokeh-app/toolkit.py

Make it possible to plot all months together in one plot, and include a line that plots all of the monthly data as a time series.

Multiple month plot

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py

Fix version numbering and data source information

---

bokeh-app/monthly/main.py

Add lines to monthly data

---

bokeh-app/monthly/main.py
bokeh-app/toolkit.py

Dynamically update monthly offset

---

bokeh-app/monthly/main.py

Make sure the lines between the data points are updated to use the selected colour map.

Fix colour map

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py

Make some minor fixes to the layout to reduce the amount of dead space in the figure that causes it to use more space than in available. This does not completely fix the issue, for that we need to update the code to use Panel 1.x and Bokeh 3.x, but these versions still have some bugs that need to be sorted out before we can switch to them.

Change layout

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/toolkit.py

Title fixes

---

bokeh-app/monthly/main.py
bokeh-app/toolkit.py

Implement decadal trend functionality

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/toolkit.py

Change data source

---

bokeh-app/toolkit.py

Make sure min and max values are ranked in the same manner

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/toolkit.py

Change text with info about data

---

bokeh-app/toolkit.py

Remove min/max dots for 1978

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py

Fix rank formatting

---

requirements.txt

Add param to requirements file.

Add missing dependency to requirements.txt

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/toolkit.py

This pull request implements anomaly plotting for the daily plots. You can now plot the anomaly relative to the mean of either 1981-2010 or 1991-2020. The code is not very clean, but it's meant as more of a proof of concept that will be cleaned up at a later point. Either way, we have to make major changes to the code once we start to pre-calculate and store it as netCDF files for improved performance.

Daily anomaly plot

---

bokeh-app/daily/main.py
bokeh-app/toolkit.py

Anomaly dots

---

bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/toolkit.py
requirements.txt

This pull request does the following:
* Upgrade packages to latest versions.
* Fix a bug where the glyph colours wouldn't update properly due to a missing argument in a function call.
* Fix a typo in thredds URL where the data is fetched from (no idea how this hasn't triggered any issues).

Upgrade packages and fix some issues

---

.gitignore
Dockerfile
README.md
bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/toolkit.py
compose.yaml
requirements.txt

This is using latest stable version of main python docker image and upgrades the software dependency.
I added a panel decorator (pn.cache) which in theory should speed up a little bit the app loading time.

Upgrade main python and depenency 

---

Dockerfile
bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/plot_tools.py
bokeh-app/toolkit.py
requirements.txt

A larger rewrite has been carried out so that classes are used more in the code, and the we are now using pre-calculated data to speed up the apps. Currently, only data from the Northern hemisphere is available on the server we fetch data from, but this will eventually change as testing is finished and the code goes into production.

Use precalculated files

---

bokeh-app/toolkit.py

Change data URLs to new ones that also include data from regions other than the northern hemisphere.

Use new URLs

---

Dockerfile
bokeh-app/daily/main.py
bokeh-app/monthly/main.py
bokeh-app/plot_tools.py
bokeh-app/toolkit.py
requirements.txt

Use pre-calculated files for producing the visualisation.

Use new files

---

bokeh-app/monthly/main.py
bokeh-app/plot_tools.py
bokeh-app/toolkit.py

Adds functionality for plotting monthly anomalies, which can be done by selecting either absolute values or anomalies in the new plot type widget. Relative trends do not make sense when plotting anomalies which is why these are not removed from the hovertool when anomalies are the selected plot type.

Monthly anomalies
