bokeh-app/main.py
This PR consists of two commits:
- The first one removes some de-duplication code that is not needed due to `nv=0` already being selected in the data. I've checked to be sure that this doesn't remove any attributes from the data.
- The second one deals with the issue of leap years. The approach I've chosen is to convert all years to leap years and to fill February 29th with data interpolated between February 28th and March 1st for non-leap years.
=> Convert all years to leap years

bokeh-app/main.py, bokeh-app/toolkit.py
Add a zoom shortcut dropdown menu, and fix the min/max calculation so that it doesn't include the current year.
Resolves #21.
=> Add zoom shortcut and fix min/max calculation

bokeh-app/main.py
I've added the decades to the same dropdown menu as the other reference periods used for the climatology. @TomLav you only mentioned the median and 25-75 percentile in the issue, but in this PR I'm also plotting the 10-90 percentile. Do you only want the 25-75 percentile to be plotted?
Here's the binder instance: https://mybinder.org/v2/gh/huaracheguarache/sea-ice-index-viz/new_climatology?urlpath=%2Fproxy%2F5006%2Fbokeh-app
Closes #12.
=> Add decade selection to climatology

bokeh-app/main.py
Setting the y-range manually to a range spanning the minimum and maximum value of the daily data in addition to some padding solves this issue.
Resolves #21.
=> Manually set y-range for preset zoom levels

bokeh-app/main.py, bokeh-app/toolkit.py
This PR does the following:
- Implements a method for calculating the rank of values for a specific day of the year.
- Changes the hovertool of the individual yearly data to a custom hovertool so that the values of the index can be shown with a unit suffix.
- Removes the hovertools for the minimum and maximum values due the potential confusion they can cause for the user.
Resolves #16.
=> Hovertool improvements

bokeh-app/main.py
Fix the custom zoom reset in the zoom shotcut dropdown menu, and remove the
superfluous zoom reset button from the toolbar. Remove help button from
toolbar since it's of limited usefulness.
=> Fix zoom reset and remove help button

bokeh-app/main.py
Instead of calculating the percentiles and median for the default reference period as was the intended behaviour, these climatologies were calculated for the entire length of the data. This happened because the data passed to the functions that calculate the percentiles and medians was never sliced to the reference period. Fix this.
Fixes #43.
=> Fix initial calculation of climatology

bokeh-app/toolkit.py
During testing it was uncovered that data from the last couple of days does not get plotted. It is suspected that this could have something to do with caching. Disable this for now to see if it resolves the issue.
=> Disable xarray caching

bokeh-app/main.py, bokeh-app/toolkit.py
* Make viridis the default colour map as it's CVD friendly, and change the order of the colour maps in the dropdown selection list.
* Change the current year to be plotted as two lines, one dashed white line on top of a thick solid black line. This ensures that the resulting line is easily distinguishable from other dashed black lines.
=> Change colour of the yearly data

bokeh-app/main.py
Plot shortcuts were broken as the last year is now plotted as two lines on top of each other. Fix this by accounting for two lines instead of one.
=> Plot shortcuts bugfix

bokeh-app/main.py
The glyph of the current year is assigned to a different variable after the change made to plot the current year as two lines. Use this variable in the calculation of the centred zoom.
=> Centred zoom bugfix

bokeh-app/main.py
* Make the min/max lines thinner to prevent them bleeding through the edges of the yearly lines. Change the dashed pattern to a denser pattern so that the lines are able to represent all the small-scale changes.
* Make the dash pattern of the white filler line of the current year denser.
=> Visual tweaks

bokeh-app/main.py
Make sure the callback that updates the data fetches the zoom state to move view to the same zoom level as previously selected.
Signed-off-by: Michael Yartys <michael.yartys@protonmail.com>
=> main: fix zoom state

bokeh-app/main.py
Change the markers for the maximum yearly index value to circles instead of triangles.
=> Change max markers to circles

bokeh-app/main.py
The code has been updated to use Panel callbacks and support URL parameters. At this time, the following parameters are supported:
* Index
* Area
* Reference period
* Plot shortcuts
* Zoom shortcuts
* Colour scale
The URL parameters are not able to track custom changes to which glyphs are visible.
The plot shortcuts have gotten the following changes:
* Erase/show all: a bugfix that makes sure that the value of the current year outline is set in addition to the filler.
* Last 5 years and 2 years: show reference period climatology and the current year, and hide yearly min/max dots.
=> Use implement URL parameters and change plot shortcuts

bokeh-app/main.py, bokeh-app/toolkit.py
This PR adds support for the new version of the sea ice data. Specifying the version of data is done in the URL by adding `?version=` to the end of the URL together with either `v2` or `v3`.
=> Add support for v3 of sea ice data

bokeh-app/main.py, bokeh-app/toolkit.py
Use version names "v2p1" and "v3p0test" in the URL parameter to be more in line with the version names from the dataset, and to emphasise that version 3.0 is a test version.
=> Version fix

bokeh-app/main.py
This PR does the following:
* Fixes a bug where the zoom level was incorrectly updated before the min/max day was recalculated during a data update.
* Changes the code to use the median values for each day of year to find the day of year with the minimum and maximum values. This makes sure that the min/max shortcuts are centred on a day that better represents the min/max points of the data (less affected by outliers).
* Removes an unused import.
* Removes the buttons that hide/show the hovertools.
=> Minor fixes and improvements

bokeh-app/main.py
The following has been done:
* Include a missing panel extension to silence a warning.
* Remove the "Under development" label.
* Use GridSpec to fix the issue where the plot doesn't use all of the available screen space.
=> A couple small fixes and adjustments

bokeh-app/monthly/main.py
Make sure that the absolute trend is printed with a single decimal to avoid diplaying a relative trend of zero when it is small. Always display the signs of the relative and absolute trends.
=> monthly: improve trend display precision and always show signs

bokeh-app/daily/main.py, bokeh-app/monthly/main.py, bokeh-app/toolkit.py
Sometimes it's useful to have reversed sequential colour maps if you want recent years (daily) or the latter part of the year (monthly) to have more contrast with the background.
=> Add reversed sequential colour maps

bokeh-app/daily/main.py, bokeh-app/toolkit.py
This pull request changes the daily plot to calculate the y-range in such a way that it takes the height of the text label in the lower left corner into account to not have any plot elements overlapping with it. The y-range is calculated for all plot shortcuts, and also when the plot is opened. The start and end values also get a small amount of padding to ensure that no plot elements are touching the top of the plot frame or the top of the text label. This leads to the y-range often containing negative y-values. A thick grey line has therefore been added on y=0 to make it stand out.
Here are some screenshots showing what this looks like for a few regions:
Resolves #114.
=> Prevent plot lines from overlapping with text label

bokeh-app/daily/main.py
Make sure variable name is "Index:" in hovertools when plot type is set to absolute values, and "Anomaly:" when plot type is set to anomalies. Also simplify the way variable formatting happens.
=> Update variable name in hovertools
